[package]
name = "window_r5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opener = "0.5.0"
regex = "1.5"
open = "1"
